package oop.koyomia.boomberman.Effects;

public enum EffectType {
    SUDDEN_DEATH, SLOW_DOWN, FIRE_BURN, EXPLOSION, SLOW_DOWN_NON_DUP, EXPLOSION_NON_DUP, TIMED_SLOW_DOWN_NON_DUP, FAST_UP, FAST_UP_NON_DUP, TIMED_FAST_UP_NON_DUP, ADD_REMOTE_BOMB_EQUIPMENT
}
